// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDja0zawHfvJOnePi5OEn7FNquQactVfLY',
    appId: '1:1087239679773:android:74faee73e2f0e705fc7bf4',
    messagingSenderId: '1087239679773',
    projectId: 'kickmyb-tupayachi',
    storageBucket: 'kickmyb-tupayachi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBka_QcuRAsQrz7HTgyt15LicjxrlzbLYA',
    appId: '1:1087239679773:ios:5b181bd43319e2ddfc7bf4',
    messagingSenderId: '1087239679773',
    projectId: 'kickmyb-tupayachi',
    storageBucket: 'kickmyb-tupayachi.firebasestorage.app',
    iosClientId: '1087239679773-23qrvv3nhglskhoobi3mq43fpmg6r44o.apps.googleusercontent.com',
    iosBundleId: 'org.tupayachi.tp1Tp2Flutter',
  );

}